# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.api.streaming_api import StreamingApi  # noqa: E501
from ibkr_client.rest import ApiException


class TestStreamingApi(unittest.TestCase):
    """StreamingApi unit test stubs"""

    def setUp(self):
        self.api = ibkr_client.api.streaming_api.StreamingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ws_post(self):
        """Test case for ws_post

        Websocket Endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
