# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.models.futures_inner import FuturesInner  # noqa: E501
from ibkr_client.rest import ApiException


class TestFuturesInner(unittest.TestCase):
    """FuturesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFuturesInner(self):
        """Test FuturesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ibkr_client.models.futures_inner.FuturesInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
