# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.models.inline_response20024_filter_list import InlineResponse20024FilterList  # noqa: E501
from ibkr_client.rest import ApiException


class TestInlineResponse20024FilterList(unittest.TestCase):
    """InlineResponse20024FilterList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20024FilterList(self):
        """Test InlineResponse20024FilterList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ibkr_client.models.inline_response20024_filter_list.InlineResponse20024FilterList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
