# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.models.inline_response20027_trading_times import InlineResponse20027TradingTimes  # noqa: E501
from ibkr_client.rest import ApiException


class TestInlineResponse20027TradingTimes(unittest.TestCase):
    """InlineResponse20027TradingTimes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20027TradingTimes(self):
        """Test InlineResponse20027TradingTimes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ibkr_client.models.inline_response20027_trading_times.InlineResponse20027TradingTimes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
