# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.models.body8 import Body8  # noqa: E501
from ibkr_client.rest import ApiException


class TestBody8(unittest.TestCase):
    """Body8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody8(self):
        """Test Body8"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ibkr_client.models.body8.Body8()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
