# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.models.iserversecdefsearch_sections import IserversecdefsearchSections  # noqa: E501
from ibkr_client.rest import ApiException


class TestIserversecdefsearchSections(unittest.TestCase):
    """IserversecdefsearchSections unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIserversecdefsearchSections(self):
        """Test IserversecdefsearchSections"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ibkr_client.models.iserversecdefsearch_sections.IserversecdefsearchSections()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
