# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.models.stocks_inner import StocksInner  # noqa: E501
from ibkr_client.rest import ApiException


class TestStocksInner(unittest.TestCase):
    """StocksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStocksInner(self):
        """Test StocksInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ibkr_client.models.stocks_inner.StocksInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
