# coding: utf-8

"""
    Client Portal Web API

    Production version of the Client Portal Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ibkr_client
from ibkr_client.api.pn_l_api import PnLApi  # noqa: E501
from ibkr_client.rest import ApiException


class TestPnLApi(unittest.TestCase):
    """PnLApi unit test stubs"""

    def setUp(self):
        self.api = ibkr_client.api.pn_l_api.PnLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_iserver_account_pnl_partitioned_get(self):
        """Test case for iserver_account_pnl_partitioned_get

        PnL for the selected account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
